### ISSUE TITLE
Better default sorting

### ISSUE THREAD

**Issue by cassidyjames** [elementary/store#26]
It's unclear what the ordering is for products right now; maybe the order they were added? We should sort them alphabetically, and/or by price, or something.

**Comment by btkostner** [comment]
Update: I have the categories order hard set as follows:
```
   "T-Shirt"
   "Outerwear"
   "Mug"
   "Poster"
   ...everything else
```

The products are just sorted by name, but not very smartly (The vala stuff is all at the end because of the `“”`).

I can update the text sorting to be a bit smarter and ignore special characters. That might make it feel a bit more natural. Otherwise I can update to sort the products by starting price instead.

**Comment by cassidyjames** [comment]
@btkostner yeah I feel like price and then alphabetical (ignoring special characters) might make sense.

**Comment by btkostner** [comment]
Sorted by category, product starting price, then name:

![localhost_4000_ (1)](https://user-images.githubusercontent.com/3385679/106373210-7d813100-6334-11eb-91eb-5a6c7cf7acc8.png)

**Comment by cassidyjames** [comment]
So this sorting still looks weird to me; the Terminal Tees should be next to each other, but aren't…

**Comment by cassidyjames** [comment]
Oh I re-read and saw that price is the default. I probably said to do that, but I think within the categories we might just want to go by alphabetical order so i.e. the Terminal and Vala tees are always going to be next to their different style counterparts.
